const dataTable = [
  {
    id: 1,
    stt: 1,
    name: 'Nguyễn Văn A',
    dateofbirth: 32,
    phone: '0978126797',
    position: 'giám đốc',
    rank: 'thượng sĩ',
    tags: 'trung ương',
  },
  {
    id: 2,
    key: '2',
    name: 'Nguyễn Văn B',
    dateofbirth: 28,
    phone: '0988026782',
    position: 'trưởng phòng',
    rank: 'trung sĩ',
    tags: 'trung ương',
  },
  {
    id: 3,
    key: '3',
    name: 'Nguyễn Văn C',
    dateofbirth: 24,
    phone: '0988026782',
    position: 'nhân viên',
    rank: 'thượng tá',
    tags: 'Hà Nội',
  },

  {
    id: 4,
    key: '4',
    stt: 4,
    name: 'Nguyễn Văn B',
    dateofbirth: 26,
    phone: '0988026782',
    position: 'trưởng phòng',
    rank: 'thượng sĩ',
    tags: 'trung ương',
  },
  {
    id: 5,
    key: '5',
    stt: 5,
    name: 'Nguyễn Văn B',
    dateofbirth: 28,
    phone: '0988026782',
    position: 'trưởng phòng',
    rank: 'thượng sĩ',
    tags: 'trung ương',
  },
]
export default dataTable